version: '3'

services:
  traefik:
    network_mode: "host"
    # The official v2 Traefik docker image
    image: traefik:v2.5
    # Enables the web UI and tells Traefik to listen to docker
    #ports:
    #  - "80:80"
    #  - "443:443"
    #  - "8080:8080"

    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./configs/:/configs/
      - ./certs/:/certs/

  rproxy:
    network_mode: "host"
    image: ruby:3.0.2
    env_file:
      - ./.env
    build:
      context: .

    command: "ruby server.rb"

    volumes:
        - ./configs/:/configs/
        - ./certs/:/certs/
