providers:
  file:
    directory: /configs
    watch: true

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

api:
  insecure: false

log:
  level: DEBUG

http:
  middlewares:
    limit:
      buffering:
        maxResponseBodyBytes: 10000000
        maxRequestBodyBytes: 10000000
    https:
        redirectScheme:
          scheme: https

    #redirecttohttps:
    #  redirectScheme:
    #    scheme: https
