
http:

  routers:
    router-catchall:
      rule: hostregexp(`{host:.+}`)
      service: "service-default"
      entryPoints:
        - websecure
      middlewares:
        - rateLimitGlobal
      tls: {}

    router-catchall-http:
      rule: hostregexp(`{host:.+}`)
      service: "service-default"
      entryPoints:
        - web
      middlewares:
        - rateLimitGlobal

  services:
    service-default:
      loadBalancer:
        passHostHeader: false
        servers:
        - url: "https://localhost:65000"

  middlewares:
    rateLimitGlobal:
        rateLimit:
          average: 50
          burst: 25
          period: 10s


