name: End-to-end

on:
  push:

jobs:
  end-to-end:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      
      -
        name: boot
        run: |
          cp .test.env .env

          docker-compose up -d --build
          sleep 10

          docker ps -a
