name: End-to-end

on:
  push:

jobs:
  end-to-end:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      
      -
        name: boot
        run: |
          cp .test.env .env

          docker-compose up -d --build
          node test/openode_api.js &
          sleep 10

          docker-compose logs
          docker ps -a

      - 
        name: test http route
        run: |

          curl -H "Host: mytest.openode.io" localhost | grep "Innovative Functionnalities"