name: End-to-end

on:
  push:

jobs:
  end-to-end:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      
      -
        name: boot
        run: |
          cp .test.env .env
          mkdir -p configs
          mkdir -p certs

          echo "dummy" > configs/dummyfile
          echo "dummy" > certs/dummyfile2

          ls -la

          node test/openode_api.js &

          # setup http shaping
          mkdir -p plugins-local/src/github.com/martinlevesque/http_shaping
          git clone https://github.com/martinlevesque/http_shaping.git plugins-local/src/github.com/martinlevesque/http_shaping

          sleep 5
          docker-compose up -d --build
          sleep 10

          docker-compose logs
          docker ps -a

      - 
        name: test http from load balancer route
        run: |

          curl -H "Host: mytest.openode.io" localhost | grep "Innovative Functionnalities"

      - 
        name: test http from boot configs
        run: |

          curl -H "Host: myboottest.openode.io" localhost | grep "{}"

      - 
        name: check removed dummy file in configs
        run: |
          if test -f "./configs/dummyfile"; then
              echo "dummyfile exists."
              exit 1
          fi

      - 
        name: check removed dummy file in certs
        run: |
          if test -f "./certs/dummyfile2"; then
              echo "dummyfile2 exists."
              exit 1
          fi
          